# -*- coding: utf-8 -*-
"""ButterflyPredictionModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHQgESMoeU4ETD0knvBLO1UoEloDPw7e
"""

# Install kaggle
!pip install kaggle

# Upload kaggle.json
from google.colab import files
files.upload()

# Setup kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Download dataset
!kaggle datasets download -d phucthaiv02/butterfly-image-classification

# Extract dataset
import zipfile

with zipfile.ZipFile("butterfly-image-classification.zip", 'r') as zip_ref:
    zip_ref.extractall("/content")

import os
os.listdir('/content')

train_dir = "/content/train"
test_dir = "/content/test"

# 1. IMPORT LIBRARIES
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os


# 2. LOAD CSV FILES
train_df = pd.read_csv('/content/Training_set.csv')
test_df = pd.read_csv('/content/Testing_set.csv')

# Correct paths
train_df['filename'] = train_df['filename'].apply(lambda x: os.path.join('/content/train', x))
test_df['filename'] = test_df['filename'].apply(lambda x: os.path.join('/content/test', x))

# 3. DATA GENERATOR (AUGMENTED)
datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=25,
    zoom_range=0.2,
    horizontal_flip=True,
    brightness_range=[0.8,1.2]
)

train_data = datagen.flow_from_dataframe(
    dataframe=train_df,
    x_col='filename',
    y_col='label',
    target_size=(160,160),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_data = datagen.flow_from_dataframe(
    dataframe=train_df,
    x_col='filename',
    y_col='label',
    target_size=(160,160),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

test_datagen = ImageDataGenerator(rescale=1./255)

test_data = test_datagen.flow_from_dataframe(
    dataframe=test_df,
    x_col='filename',
    y_col=None,
    target_size=(160,160),
    batch_size=32,
    class_mode=None,
    shuffle=False
)

# 4. MODEL (TRANSFER LEARNING)
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(160,160,3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False

num_classes = len(train_data.class_indices)

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.BatchNormalization(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(num_classes, activation='softmax')
])

# 5. COMPILE
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# 6. INITIAL TRAINING
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=15
)

# 7. FINE-TUNING
base_model.trainable = True

for layer in base_model.layers[:-30]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history_fine = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

# 8. EVALUATE
loss, accuracy = model.evaluate(val_data)
print("Validation Accuracy:", accuracy)

# 9. PLOT
plt.plot(history.history['accuracy'] + history_fine.history['accuracy'])
plt.plot(history.history['val_accuracy'] + history_fine.history['val_accuracy'])
plt.legend(['Train', 'Validation'])
plt.title('Model Accuracy')
plt.show()

# 10. PREDICT
predictions = model.predict(test_data)

predicted_classes = np.argmax(predictions, axis=1)

class_indices = train_data.class_indices
labels_map = dict((v,k) for k,v in class_indices.items())

predicted_labels = [labels_map[k] for k in predicted_classes]

# 11. SAVE SUBMISSION
submission = pd.DataFrame({
    'filename': test_df['filename'].apply(lambda x: x.split('/')[-1]),
    'label': predicted_labels
})

submission.to_csv('/content/submission.csv', index=False)

print("✅ Submission file saved!")

import gradio as gr
import numpy as np
from tensorflow.keras.preprocessing import image

# Class names
class_names = list(train_data.class_indices.keys())

def predict(img):
    img = img.resize((160,160))
    img_array = np.array(img)/255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)
    idx = np.argmax(prediction)
    confidence = prediction[0][idx] * 100

    return f"🦋 {class_names[idx]} ({confidence:.2f}%)"

# Create interface
app = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="🦋 Butterfly Classifier"
)

app.launch(share=True)